---
- name: Enable automatic updates
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::AutocleanInterval "7";

- name: Configure unattended-upgrades for automatic reboot
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/51unattended-upgrades-reboot
    owner: root
    group: root
    mode: "0644"
    content: |
      Unattended-Upgrade::Automatic-Reboot "true";
      Unattended-Upgrade::Automatic-Reboot-Time "03:30";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
